server:
  port: 8099
  servlet:
    context-path: /market

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/market?currentSchema=example_data
    username: user1
    password: 1111
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL95Dialect
